[package]
name = "nexus_core"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
tracing = "0.1.40"
axum = "0.7.7"


nexus_router = {path="../nexus_router"}
nexus_error = {path="../nexus_error"}